import * as MuiMaterial from "@mui/material";

export const material = {
  Box: MuiMaterial.Box,
  Container: MuiMaterial.Container,
  Grid: MuiMaterial.Grid,
  Typography: MuiMaterial.Typography,
  Button: MuiMaterial.Button,
  TextField: MuiMaterial.TextField,
  Dialog: MuiMaterial.Dialog,
  DialogTitle: MuiMaterial.DialogTitle,
  DialogContent: MuiMaterial.DialogContent,
  DialogContentText: MuiMaterial.DialogContentText,
  DialogActions: MuiMaterial.DialogActions,
  FormControl: MuiMaterial.FormControl,
  InputLabel: MuiMaterial.InputLabel,
  Select: MuiMaterial.Select,
  MenuItem: MuiMaterial.MenuItem,
  CircularProgress: MuiMaterial.CircularProgress,
  Paper: MuiMaterial.Paper,
  IconButton: MuiMaterial.IconButton,
  Tooltip: MuiMaterial.Tooltip,
  AppBar: MuiMaterial.AppBar,
  Toolbar: MuiMaterial.Toolbar,
  Avatar: MuiMaterial.Avatar,
  CssBaseline: MuiMaterial.CssBaseline,
  Stack: MuiMaterial.Stack,
  Card: MuiMaterial.Card,
  CardContent: MuiMaterial.CardContent,
  CardMedia: MuiMaterial.CardMedia,
  Divider: MuiMaterial.Divider,
  Chip: MuiMaterial.Chip,
  ThemeProvider: MuiMaterial.ThemeProvider,
  Drawer: MuiMaterial.Drawer,
  List: MuiMaterial.List,
  ListItem: MuiMaterial.ListItem,
  ListItemButton: MuiMaterial.ListItemButton,
  ListItemText: MuiMaterial.ListItemText,
} as const;
